wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    code_path: code/seq2seq.py
    framework: huggingface
    huggingface_version: 4.27.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1677964315.624693
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      2:
      - 1
      - 11
      - 49
      - 55
      - 71
      3:
      - 13
      - 23
      4: 3.10.9
      5: 0.13.10
      6: 4.27.0.dev0
      8:
      - 3
      - 5
